### ISSUE TITLE
Supression of missing & unexpected arguments to queryset calls is failing

### ISSUE THREAD

**Issue by macdjord** [jucacrispim/pylint-mongoengine#8] opened 2019-06-18 05:21 UTC
Calls to querysets are not being detected and therefore errors about missing and unexpected arguments are not being suppressed.

The problem is in `suppression.py`, line 35; `dec.name` should be `dec.attrname`

**Comment by jucacrispim** [comment] 2019-06-19 09:18
Thank you very much for your help!

Can you provide some piece of code causing the errors? I couldn't reproduce it.

**Comment by macdjord** [comment] 2019-06-21 07:16
```python
import mongoengine as _me


class MyDoc(_me.Document):
    my_field = _me.StringField()

    @_me.queryset_manager
    def my_query(doc_cls, queryset: _me.QuerySet) -> _me.QuerySet:
        return queryset(my_field__ne='foo')


def my_func():
    print(MyDoc.my_query(my_field='bar'))  # <- Generates "Unexpected keyword argument 'my_field' " and "No value for argument 'doc_cls' " lint warnings
```

**Comment by jucacrispim** [comment] 2019-06-22 07:46
Thank you!

It's fixed on master and `pylint-mongoengine==0.3.2` is on PyPI

**Closed as completed by jucacrispim** 2019-06-22 07:46 UTC
